# Generated by Django 4.1 on 2023-04-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.CharField(max_length=20)),
                ("userPassword", models.CharField(max_length=20)),
                ("userRealName", models.CharField(max_length=10)),
                ("userEmail", models.EmailField(max_length=30)),
            ],
        ),
    ]
