# Generated by Django 4.2 on 2023-05-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugInfo",
            fields=[
                (
                    "drugNo",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=9,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drugName", models.CharField(max_length=25)),
                ("drugEffect", models.CharField(max_length=50)),
                ("component", models.CharField(max_length=50)),
                ("quantity", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="PillData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescId",
                    models.DecimalField(decimal_places=0, max_digits=13, null=True),
                ),
                (
                    "drugNo",
                    models.DecimalField(decimal_places=0, max_digits=9, null=True),
                ),
                ("pillShape", models.TextField(max_length=6)),
                ("pillColor", models.TextField(max_length=20)),
                ("pillText", models.TextField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "prescId",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=13,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescDate", models.DateField(default="")),
                ("dispensary", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.CharField(max_length=12)),
                ("userPassword", models.CharField(max_length=20)),
                ("userRealName", models.CharField(max_length=10)),
                ("userEmail", models.EmailField(max_length=25)),
                ("userRegisterDatetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("startDate", models.DateField(default="")),
                ("endDate", models.DateField(default="")),
                (
                    "prescId",
                    models.ForeignKey(
                        db_column="prescId",
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="schedule",
                        serialize=False,
                        to="users.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prescId", models.DecimalField(decimal_places=0, max_digits=13)),
                ("drugNo", models.DecimalField(decimal_places=0, max_digits=9)),
                ("dosagePerOnce", models.IntegerField()),
                ("dailyDose", models.IntegerField()),
                ("totalDosingDays", models.IntegerField()),
                (
                    "scheduleId",
                    models.ForeignKey(
                        db_column="scheduleId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="PrescDetail",
                        to="users.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrugHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugNo", models.DecimalField(decimal_places=0, max_digits=9)),
                ("hour", models.TimeField()),
                (
                    "scheduleId",
                    models.ForeignKey(
                        db_column="scheduleId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drugHour",
                        to="users.schedule",
                    ),
                ),
            ],
        ),
    ]
