# Generated by Django 4.2 on 2023-06-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drughour",
            name="id",
        ),
        migrations.RemoveField(
            model_name="drughour",
            name="prescDetail",
        ),
        migrations.AddField(
            model_name="schedule",
            name="maxDoseHours",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="drughour",
            name="schedule",
            field=models.ForeignKey(
                db_column="schedule",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="drugHour",
                serialize=False,
                to="users.schedule",
            ),
        ),
    ]
